# Generated by Django 5.2 on 2026-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='transcribe_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
